### ISSUE TITLE
Feature request - add a setting whether gesture maximizes a window or makes it fullscreen

### ISSUE THREAD

**Issue by marcin-makulec** [diredocks/gesture-evolution#1]
Title says it all. BTW great work, thank you very much!

**Comment by diredocks** [comment]
~~Unfortunately, implementing these features isn't currently feasible due to the limitations of the KWin script API. I'm actively learning the KWin code base and working on incorporating these features. The KDE developers have been discussing touchpad/touchscreen gestures and mouse gestures, but it's still in the early stages.~~

I apologize for any confusion earlier; upon further exploration, I've discovered it is indeed feasible. I'll proceed to create a configuration window where you can easily control these features.

https://invent.kde.org/plasma/kwin/-/issues/59

**Comment by diredocks** [comment]
Done, try the latest commit.

**Comment by marcin-makulec** [comment]
Thanks! It seems that checkboxes do the exact opposite of what the labels say - I disabled them and now it works flawlessly. Simple negation and changing the default state should suffice
![obraz](https://github.com/diredocks/gesture-evolution/assets/76711626/44fd543a-7b95-4905-87bd-568cae489b99)
